---
title: "Child Sex Exploration"
subtitle: "Vital Statistics"
author: "Christopher Boyd, MPA"
output:
  tufte::tufte_html: default
bibliography: skeleton.bib
link-citations: yes
---

```{r setup, echo=FALSE}
knitr::read_chunk('chunks.R')
library(knitr)
library(tufte)
suppressMessages(library(vitalstatistics))
suppressMessages(library(dplyr))
library(ggplot2)
```

```{r page-defaults, echo=FALSE, results='asis'}
```

`r tufte::margin_note('[Home Page](index)')`
`r tufte::margin_note('[Directory](directory)')`

# Summary

...

```{r}
b = copy(births)
```

```{r}
ext.birth_decade(b)
```


```{r, fig.height=8}
b %>%
  filter(!is.na(birth_state)) %>%
  group_by(birth_state) %>%
  mutate(state_size = sum(cases)) %>%
  group_by(
    birth_decade,
    birth_state,
    child_sex
  ) %>%
  summarize(cases = sum(cases)) %>%
  group_by(
    birth_state,
    birth_decade
  ) %>%
  mutate(male_share = cases / sum(cases)) %>%
  filter(child_sex=='Male') %>%
  ggplot(aes(male_share, birth_state, color=birth_decade)) +
    geom_point(stat = "identity") +
    geom_vline(xintercept = 0.5, color='pink')
    # facet_grid(. ~ birth_decade)
```
